sudo: required

services: 
        - docker

before_install:
        - docker build -t walidghallab/react-test -f ./client/Dockerfile.dev ./client

script: 
        - docker run -e CI=true walidghallab/react-test npm test

after_success:
        - docker build -t walidghallab/multi-client ./client
        - docker build -t walidghallab/multi-nginx ./nginx
        - docker build -t walidghallab/multi-server ./server
        - docker build -t walidghallab/multi-worker ./worker
        # Log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        # Pushing images to docker hub
        - docker push walidghallab/multi-client
        - docker push walidghallab/multi-nginx
        - docker push walidghallab/multi-server
        - docker push walidghallab/multi-worker

deploy:
        provider: elasticbeanstalk
        region: us-east-2
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-2-890874224471
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: "$AWS_ACCESS_KEY"
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
